wandb_version: 1

activation:
  value: LeakyReLU
batch_size:
  value: 64
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_layers:
  value: 3
weight_decay:
  value: 0.0001
