_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 14
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
activation:
    value: ReLU
batch_size:
    value: 64
epochs:
    value: 10
hidden_size:
    value: 1024
learning_rate:
    value: 0.001
num_layers:
    value: 5
weight_decay:
    value: 1e-05
