wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 128
conv_activation:
  value: ReLU
data_aug:
  value: false
dense_activation:
  value: ReLU
dense_size:
  value: 1024
dropout_prob:
  value: 0.3
filter_size:
  value:
  - 7
  - 7
  - 5
  - 3
  - 3
learning_rate:
  value: 0.001
n_epochs:
  value: 10
n_filter:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: kaiming
