wandb_version: 1

activation:
  value: ReLU
batch_norm:
  value: false
batch_size:
  value: 128
data_aug:
  value: true
dropout_prob:
  value: 0.5
epochs:
  value: 10
filter_size:
  value:
  - 7
  - 7
  - 5
  - 3
  - 3
hidden_size:
  value: 512
learning_rate:
  value: 0.001
n_filter:
  value:
  - 512
  - 256
  - 128
  - 64
  - 32
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: kaiming
