_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
activation:
    value: SiLU
batch_norm:
    value: true
batch_size:
    value: 256
dat_aug:
    value: false
dropout_prob:
    value: 0.5
epochs:
    value: 20
filter_size:
    value:
        - 5
        - 5
        - 5
        - 5
        - 5
hidden_size:
    value: 512
learning_rate:
    value: 0.0001
n_filter:
    value:
        - 512
        - 256
        - 128
        - 64
        - 32
num_layers:
    value: 5
optimizer:
    value: adam
weight_decay:
    value: 0.005
weight_init:
    value: default
