wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 64
conv_activation:
  value: GELU
data_aug:
  value: true
dense_activation:
  value: ReLU
dropout_prob:
  value: 0.3
epochs:
  value: 15
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
hidden_size:
  value: 1024
learning_rate:
  value: 0.0001
n_filter:
  value:
  - 512
  - 256
  - 128
  - 64
  - 32
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: kaiming
