wandb_version: 1

activation:
  value: SiLU
batch_norm:
  value: true
batch_size:
  value: 256
dat_aug:
  value: false
dropout_prob:
  value: 0.5
epochs:
  value: 20
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
hidden_size:
  value: 512
learning_rate:
  value: 0.0001
n_filter:
  value:
  - 512
  - 256
  - 128
  - 64
  - 32
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: default
