wandb_version: 1

activation:
  value: GELU
batch_norm:
  value: false
batch_size:
  value: 128
dat_aug:
  value: true
dropout_prob:
  value: 0.5
epochs:
  value: 20
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
hidden_size:
  value: 512
learning_rate:
  value: 0.0005
n_filter:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: kaiming
