wandb_version: 1

activation:
  value: SiLU
batch_norm:
  value: false
batch_size:
  value: 256
dropout_prob:
  value: 0.3
epochs:
  value: 20
hidden_size:
  value: 512
learning_rate:
  value: 0.001
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: default
