wandb_version: 1

activation:
  value: ReLU
batch_norm:
  value: false
batch_size:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 20
hidden_size:
  value: 512
learning_rate:
  value: 0.0001
num_layers:
  value: 5
optimizer:
  value: sgd
weight_decay:
  value: 5.0e-05
weight_init:
  value: xavier
