wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 128
conv_activation:
  value: GELU
data_aug:
  value: false
dense_activation:
  value: ReLU
dropout_prob:
  value: 0.5
epochs:
  value: 20
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
hidden_size:
  value: 1024
learning_rate:
  value: 0.0005
n_filters:
  value:
  - 512
  - 256
  - 128
  - 64
  - 32
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: xavier
