wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 128
conv_activation:
  value: SiLU
data_aug:
  value: false
dense_activation:
  value: ReLU
dropout_prob:
  value: 0.3
epochs:
  value: 20
filter_size:
  value:
  - 7
  - 7
  - 5
  - 3
  - 3
hidden_size:
  value: 1024
learning_rate:
  value: 0.0001
n_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: xavier
