wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 256
epochs:
  value: 10
hidden_size:
  value: 1024
learning_rate:
  value: 0.001
num_layers:
  value: 5
weight_decay:
  value: 5.0e-05
