_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
activation:
    value: ReLU
batch_norm:
    value: false
batch_size:
    value: 128
dropout_rate:
    value: 0.3
epochs:
    value: 20
hidden_size:
    value: 512
learning_rate:
    value: 0.0001
num_layers:
    value: 5
optimizer:
    value: sgd
weight_decay:
    value: 5e-05
weight_init:
    value: xavier
