wandb_version: 1

activation:
  value: ReLU
batch_norm:
  value: true
batch_size:
  value: 128
dropout_rate:
  value: 0.3
epochs:
  value: 20
hidden_size:
  value: 1024
learning_rate:
  value: 0.001
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 1.0e-05
weight_init:
  value: default
