wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 256
conv_activation:
  value: SiLU
data_aug:
  value: false
dropout_prob:
  value: 0.3
epochs:
  value: 10
filter_size:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
hidden_size:
  value: 1024
learning_rate:
  value: 0.0005
n_filter:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: xavier
