_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 256
learning_rate:
    value: 0.00011987689446181132
weight_decay:
    value: 0.00025765147944928514
