_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
activation:
    value: LeakyReLU
batch_size:
    value: 32
epochs:
    value: 10
hidden_size:
    value: 64
learning_rate:
    value: 0.0001
num_layers:
    value: 3
weight_decay:
    value: 0.001
