wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 256
epochs:
  value: 15
hidden_size:
  value: 1024
learning_rate:
  value: 0.0001
num_layers:
  value: 5
weight_decay:
  value: 1.0e-05
