wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 64
conv_activation:
  value: ReLU
data_aug:
  value: true
dense_activation:
  value: ReLU
dense_size:
  value: 512
dropout_prob:
  value: 0.5
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
learning_rate:
  value: 0.0001
n_epochs:
  value: 15
n_filter:
  value:
  - 64
  - 64
  - 64
  - 64
  - 64
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.005
weight_init:
  value: kaiming
