wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 128
conv_activation:
  value: GELU
data_aug:
  value: true
dense_activation:
  value: ReLU
dense_size:
  value: 512
dropout_prob:
  value: 0.3
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
learning_rate:
  value: 0.0001
n_epochs:
  value: 15
n_filter:
  value:
  - 256
  - 128
  - 64
  - 32
  - 16
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: xavier
