wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 256
conv_activation:
  value: SiLU
data_aug:
  value: false
dense_activation:
  value: ReLU
dropout_prob:
  value: 0.3
epochs:
  value: 15
filter_size:
  value:
  - 7
  - 7
  - 5
  - 3
  - 3
hidden_size:
  value: 512
learning_rate:
  value: 0.0001
n_filter:
  value:
  - 512
  - 256
  - 128
  - 64
  - 32
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: kaiming
