wandb_version: 1

activation:
  value: SiLU
batch_size:
  value: 128
epochs:
  value: 20
hidden_size:
  value: 1024
learning_rate:
  value: 0.0001
num_layers:
  value: 5
weight_decay:
  value: 5.0e-05
